#ifndef ZEPHYR_DRIVERS_ETHERNET_DWMAC_ETH_EQOS_REG_H
#define ZEPHYR_DRIVERS_ETHERNET_DWMAC_ETH_EQOS_REG_H

/*
 * MAC Register Definitions
 */

#define MAC_CONFIGURATION 0x0000

#define MAC_CONFIGURATION_ARPEN  BIT(31)
#define MAC_CONFIGURATION_SARC   GENMASK(30, 28)
#define MAC_CONFIGURATION_IPC    BIT(27)
#define MAC_CONFIGURATION_IPG    GENMASK(26, 24)
#define MAC_CONFIGURATION_GPSLCE BIT(23)
#define MAC_CONFIGURATION_S2KP   BIT(22)
#define MAC_CONFIGURATION_CST    BIT(21)
#define MAC_CONFIGURATION_ACS    BIT(20)
#define MAC_CONFIGURATION_WD     BIT(19)
#define MAC_CONFIGURATION_BE     BIT(18)
#define MAC_CONFIGURATION_JD     BIT(17)
#define MAC_CONFIGURATION_JE     BIT(16)
#define MAC_CONFIGURATION_PS     BIT(15)
#define MAC_CONFIGURATION_FES    BIT(14)
#define MAC_CONFIGURATION_DM     BIT(13)
#define MAC_CONFIGURATION_LM     BIT(12)
#define MAC_CONFIGURATION_ECRSFD BIT(11)
#define MAC_CONFIGURATION_DO     BIT(10)
#define MAC_CONFIGURATION_DCRS   BIT(9)
#define MAC_CONFIGURATION_DR     BIT(8)
#define MAC_CONFIGURATION_BL     GENMASK(6, 5)
#define MAC_CONFIGURATION_DC     BIT(4)
#define MAC_CONFIGURATION_PRELEN GENMASK(3, 2)
#define MAC_CONFIGURATION_TE     BIT(1)
#define MAC_CONFIGURATION_RE     BIT(0)

#define MAC_EXT_CONFIGURATION 0x0004

#define MAC_EXT_CONFIGURATION_FHE    BIT(31)
#define MAC_EXT_CONFIGURATION_EIPG   GENMASK(29, 25)
#define MAC_EXT_CONFIGURATION_EIPGEN BIT(24)
#define MAC_EXT_CONFIGURATION_HDSMS  GENMASK(22, 20)
#define MAC_EXT_CONFIGURATION_PDC    BIT(19)
#define MAC_EXT_CONFIGURATION_USP    BIT(18)
#define MAC_EXT_CONFIGURATION_SPEN   BIT(17)
#define MAC_EXT_CONFIGURATION_DCRCC  BIT(16)
#define MAC_EXT_CONFIGURATION_GPSL   GENMASK(13, 0)

#define MAC_PACKET_FILTER 0x0008

#define MAC_PACKET_FILTER_RA   BIT(31)
#define MAC_PACKET_FILTER_DNTU BIT(21)
#define MAC_PACKET_FILTER_IPFE BIT(20)
#define MAC_PACKET_FILTER_VTFE BIT(16)
#define MAC_PACKET_FILTER_HPF  it(10)
#define MAC_PACKET_FILTER_SAF  BIT(9)
#define MAC_PACKET_FILTER_SAIF BIT(8)
#define MAC_PACKET_FILTER_PCF  GENMASK(7, 6)
#define MAC_PACKET_FILTER_DBF  BIT(5)
#define MAC_PACKET_FILTER_PM   BIT(4)
#define MAC_PACKET_FILTER_DAIF BIT(3)
#define MAC_PACKET_FILTER_HMC  BIT(2)
#define MAC_PACKET_FILTER_HUC  BIT(1)
#define MAC_PACKET_FILTER_PR   BIT(0)

#define MAC_WDOG_TIMEOUT 0x000c

#define MAC_WDOG_TIMEOUT_PWE BIT(8)
#define MAC_WDOG_TIMEOUT_WTO GENMASK(3, 0)

#define MAC_HASH_TABLE(i) (0x0010 + 4 * (i))

#define MAC_VLAN_TAG 0x0050

#define MAC_VLAN_TAG_VL      GENMASK(15, 0)
#define MAC_VLAN_TAG_ETV     BIT(16)
#define MAC_VLAN_TAG_VTIM    BIT(17)
#define MAC_VLAN_TAG_ESVL    BIT(18)
#define MAC_VLAN_TAG_ERSVLM  BIT(19)
#define MAC_VLAN_TAG_DOVLTC  BIT(20)
#define MAC_VLAN_TAG_EVLS    GENMASK(22, 21)
#define MAC_VLAN_TAG_EVLRXS  BIT(24)
#define MAC_VLAN_TAG_VTHM    BIT(25)
#define MAC_VLAN_TAG_EDVLP   BIT(26)
#define MAC_VLAN_TAG_ERIVLT  BIT(27)
#define MAC_VLAN_TAG_EIVLS   GENMASK(29, 28)
#define MAC_VLAN_TAG_EIVLRXS BIT(31)

#define MAC_VLAN_TAG_CTRL 0x0050

#define MAC_VLAN_TAG_CTRL_EIVLRXS BIT(31)
#define MAC_VLAN_TAG_CTRL_EIVLS   GENMASK(29, 28)
#define MAC_VLAN_TAG_CTRL_ERIVLT  BIT(27)
#define MAC_VLAN_TAG_CTRL_EDVLP   BIT(26)
#define MAC_VLAN_TAG_CTRL_VTHM    BIT(25)
#define MAC_VLAN_TAG_CTRL_EVLRXS  BIT(24)
#define MAC_VLAN_TAG_CTRL_EVLS    GENMASK(22, 21)
#define MAC_VLAN_TAG_CTRL_DOVLTC  BIT(20)
#define MAC_VLAN_TAG_CTRL_ERSVLM  BIT(19)
#define MAC_VLAN_TAG_CTRL_ESVL    BIT(18)
#define MAC_VLAN_TAG_CTRL_VTIM    BIT(17)
#define MAC_VLAN_TAG_CTRL_ETV     BIT(16)
#define MAC_VLAN_TAG_CTRL_VL      GENMASK(15, 0)
#define MAC_VLAN_TAG_CTRL_OFS     GENMASK(6, 2)
#define MAC_VLAN_TAG_CTRL_CT      BIT(1)
#define MAC_VLAN_TAG_CTRL_OB      BIT(0)

#define MAC_VLAN_TAG_DATA 0x0054

#define MAC_VLAN_TAG_DATA_VID     GENMASK(15, 0)
#define MAC_VLAN_TAG_DATA_VEN     BIT(16)
#define MAC_VLAN_TAG_DATA_ETV     BIT(17)
#define MAC_VLAN_TAG_DATA_DOVLTC  BIT(18)
#define MAC_VLAN_TAG_DATA_ERSVLM  BIT(19)
#define MAC_VLAN_TAG_DATA_ERIVLT  BIT(20)
#define MAC_VLAN_TAG_DATA_DMACHEN BIT(24)
#define MAC_VLAN_TAG_DATA_DMACHN  GENMASK(27, 25)

#define MAC_VLAN_HASH_TBL 0x0058

#define MAC_VLAN_INCL 0x0060

#define MAC_INNER_VLAN_INCL 0x0064

#define MAC_Qn_TX_FLOW_CTRL(i) (0x0070 + 4 * (i))

#define MAC_Qn_TX_FLOW_CTRL_PT      GENMASK(31, 16)
#define MAC_Qn_TX_FLOW_CTRL_DZPQ    BIT(7)
#define MAC_Qn_TX_FLOW_CTRL_PLT     GENMASK(6, 4)
#define MAC_Qn_TX_FLOW_CTRL_TFE     BIT(1)
#define MAC_Qn_TX_FLOW_CTRL_FCB_BPA BIT(0)

#define MAC_RX_FLOW_CTRL 0x0090

#define MAC_RX_FLOW_CTRL_PFCE BIT(8)
#define MAC_RX_FLOW_CTRL_UP   BIT(1)
#define MAC_RX_FLOW_CTRL_RFE  BIT(0)

#define MAC_RXQ_CTRL4 0x0094

#define MAC_TXQ_PRTY_MAP0 0x0098

#define MAC_TXQ_PRTY_MAP1 0x009c

#define MAC_RXQ_CTRL0               0x00a0
#define MAC_RXQ_CTRL0_RXQiEN_POS(i) (2 * n)
enum {
	MAC_RXQ_CTRL0_RXQiEN_DISABLED,
	MAC_RXQ_CTRL0_RXQiEN_AV,
	MAC_RXQ_CTRL0_RXQiEN_GENERIC
};

#define MAC_RXQ_CTRL1         0x00a4
#define MAC_RXQ_CTRL1_AVCPQ   GENMASK(2, 0)
#define MAC_RXQ_CTRL1_PTPQ    GENMASK(6, 4)
#define MAC_RXQ_CTRL1_DCBCPQ  GENMASK(10, 8)
#define MAC_RXQ_CTRL1_UPQ     GENMASK(14, 12)
#define MAC_RXQ_CTRL1_MCBCQ   GENMASK(18, 16)
#define MAC_RXQ_CTRL1_MCBCQEN BIT(21)
#define MAC_RXQ_CTRL1_TACPQE  BIT(21)
#define MAC_RXQ_CTRL1_TPQC    GENMASK(23, 22)
#define MAC_RXQ_CTRL1_FPRQ    GENMASK(26, 24)

#define MAC_RXQ_CTRL2 0x00a8
#define MAC_RXQ_CTRL3 0x00ac

#define MAC_INTERRUPT_STATUS 0x00b0

#define MAC_INTERRUPT_STATUS_MFRIS     BIT(20)
#define MAC_INTERRUPT_STATUS_MFTIS     BIT(19)
#define MAC_INTERRUPT_STATUS_MDIOIS    BIT(18)
#define MAC_INTERRUPT_STATUS_FPEIS     BIT(17)
#define MAC_INTERRUPT_STATUS_GPIIS     BIT(15)
#define MAC_INTERRUPT_STATUS_RXSTSIS   BIT(14)
#define MAC_INTERRUPT_STATUS_TXSTSIS   BIT(13)
#define MAC_INTERRUPT_STATUS_TSIS      BIT(12)
#define MAC_INTERRUPT_STATUS_MMCRXIPIS BIT(11)
#define MAC_INTERRUPT_STATUS_MMCTXIS   BIT(10)
#define MAC_INTERRUPT_STATUS_MMCRXIS   BIT(9)
#define MAC_INTERRUPT_STATUS_MMCIS     BIT(8)
#define MAC_INTERRUPT_STATUS_LPIIS     BIT(5)
#define MAC_INTERRUPT_STATUS_PMTIS     BIT(4)
#define MAC_INTERRUPT_STATUS_PHYIS     BIT(3)
#define MAC_INTERRUPT_STATUS_PCSANCIS  BIT(2)
#define MAC_INTERRUPT_STATUS_PCSLCHGIS BIT(1)
#define MAC_INTERRUPT_STATUS_RGSMIIIS  BIT(0)

#define MAC_INTERRUPT_ENABLE 0x00b4

#define MAC_INTERRUPT_ENABLE_MDIOIE    BIT(18)
#define MAC_INTERRUPT_ENABLE_FPEIE     BIT(17)
#define MAC_INTERRUPT_ENABLE_RXSTSIE   BIT(14)
#define MAC_INTERRUPT_ENABLE_TXSTSIE   BIT(13)
#define MAC_INTERRUPT_ENABLE_TSIE      BIT(12)
#define MAC_INTERRUPT_ENABLE_LPIIE     BIT(5)
#define MAC_INTERRUPT_ENABLE_PMTIE     BIT(4)
#define MAC_INTERRUPT_ENABLE_PHYIE     BIT(3)
#define MAC_INTERRUPT_ENABLE_PCSANCIE  BIT(2)
#define MAC_INTERRUPT_ENABLE_PCSLCHGIE BIT(1)
#define MAC_INTERRUPT_ENABLE_RGSMIIIE  BIT(0)

#define MAC_RX_TX_STATUS 0x00b8

#define MAC_RX_TX_STATUS_WT    BIT(8)
#define MAC_RX_TX_STATUS_EXCOL BIT(5)
#define MAC_RX_TX_STATUS_LCOL  BIT(4)
#define MAC_RX_TX_STATUS_EXDEF BIT(3)
#define MAC_RX_TX_STATUS_LCARR BIT(2)
#define MAC_RX_TX_STATUS_NCARR BIT(1)
#define MAC_RX_TX_STATUS_TJT   BIT(0)

#define MAC_PMT_CTRL_STATUS 0x00c0

#define MAC_PMT_CTRL_STATUS_RWKFILTRST BIT(31)
#define MAC_PMT_CTRL_STATUS_RWKPTR     GENMASK(28, 24)
#define MAC_PMT_CTRL_STATUS_RWKPFE     BIT(10)
#define MAC_PMT_CTRL_STATUS_GLBLUCAST  BIT(9)
#define MAC_PMT_CTRL_STATUS_RWKPRCVD   BIT(6)
#define MAC_PMT_CTRL_STATUS_MGKPRCVD   BIT(5)
#define MAC_PMT_CTRL_STATUS_RWKPKTEN   BIT(2)
#define MAC_PMT_CTRL_STATUS_MGKPKTEN   BIT(1)
#define MAC_PMT_CTRL_STATUS_PWRDWN     BIT(0)

#define MAC_RWK_PKT_FILTER 0x00c4

#define MAC_LPI_CTRL_STATUS 0x00d0

#define MAC_LPI_CTRL_STATUS_LPITCSE BIT(21)
#define MAC_LPI_CTRL_STATUS_LPIATE  BIT(20)
#define MAC_LPI_CTRL_STATUS_LPITXA  BIT(19)
#define MAC_LPI_CTRL_STATUS_PLSEN   BIT(18)
#define MAC_LPI_CTRL_STATUS_PLS     BIT(17)
#define MAC_LPI_CTRL_STATUS_LPIEN   BIT(16)
#define MAC_LPI_CTRL_STATUS_RLPIST  BIT(9)
#define MAC_LPI_CTRL_STATUS_TLPIST  BIT(8)
#define MAC_LPI_CTRL_STATUS_RLPIEX  BIT(3)
#define MAC_LPI_CTRL_STATUS_RLPIEN  BIT(2)
#define MAC_LPI_CTRL_STATUS_TLPIEX  BIT(1)
#define MAC_LPI_CTRL_STATUS_TLPIEN  BIT(0)

#define MAC_LPI_TIMERS_CTRL 0x00d4
#define MAC_LPI_ENTRY_TIMER 0x00d8
#define MAC_1US_TIC_COUNTERR 0x00dc

#define MAC_AN_CTRL 0x00e0

#define MAC_AN_CTRL_SGMRAL BIT(18)
#define MAC_AN_CTRL_LR     BIT(17)
#define MAC_AN_CTRL_ECD    BIT(16)
#define MAC_AN_CTRL_ELE    BIT(14)
#define MAC_AN_CTRL_ANE    BIT(12)
#define MAC_AN_CTRL_RAN    BIT(9)

#define MAC_AN_STATUS 0x00e4

#define MAC_AN_STATUS_ES  BIT(8)
#define MAC_AN_STATUS_ANC BIT(5)
#define MAC_AN_STATUS_ANA BIT(3)
#define MAC_AN_STATUS_LS  BIT(2)

#define MAC_AN_ADVERT 0x00e8

#define MAC_AN_ADVERT_NP  BIT(15)
#define MAC_AN_ADVERT_RFE GENMASK(13, 12)
#define MAC_AN_ADVERT_PSE GENMASK(8, 7)
#define MAC_AN_ADVERT_HD  BIT(6)
#define MAC_AN_ADVERT_FD  BIT(5)

#define MAC_AN_LINK_PRTNR 0x00ec

#define MAC_AN_LINK_PRTNR_NP  BIT(15)
#define MAC_AN_LINK_PRTNR_ACK BIT(14)
#define MAC_AN_LINK_PRTNR_RFE GENMASK(13, 12)
#define MAC_AN_LINK_PRTNR_PSE GENMASK(8, 7)
#define MAC_AN_LINK_PRTNR_HD  BIT(6)
#define MAC_AN_LINK_PRTNR_FD  BIT(5)

#define MAC_AN_EXPANSION 0x00f0

#define MAC_AN_EXPANSION_NPA BIT(2)
#define MAC_AN_EXPANSION_NPR BIT(1)

#define MAC_TBI_EXT_STATUS 0x00f4

#define MAC_TBI_EXT_STATUS_GFD BIT(15)
#define MAC_TBI_EXT_STATUS_GHD BIT(14)

#define MAC_PHYIF_CTRL_STATUS 0x00f8

#define MAC_PHYIF_CTRL_STATUS_FALSCARDET BIT(21)
#define MAC_PHYIF_CTRL_STATUS_JABTO      BIT(20)
#define MAC_PHYIF_CTRL_STATUS_LNKSTS     BIT(19)
#define MAC_PHYIF_CTRL_STATUS_LNKSPEED   GENMASK(18, 17)
#define MAC_PHYIF_CTRL_STATUS_LNKMOD     BIT(16)
#define MAC_PHYIF_CTRL_STATUS_SMIDRXS    BIT(4)
#define MAC_PHYIF_CTRL_STATUS_SFTERR     BIT(2)
#define MAC_PHYIF_CTRL_STATUS_LUD        BIT(1)
#define MAC_PHYIF_CTRL_STATUS_TC         BIT(0)

#define MAC_VERSION 0x0110

#define MAC_VERSION_USERVER GENMASK(15, 8)
#define MAC_VERSION_SNPSVER GENMASK(7, 0)

#define MAC_DEBUG 0x0114

#define MAC_HW_FEATURE0 0x011c

#define MAC_HW_FEATURE0_ACTPHYSEL    GENMASK(30, 28)
#define MAC_HW_FEATURE0_SAVLANINS    BIT(27)
#define MAC_HW_FEATURE0_TSSTSSEL     GENMASK(26, 25)
#define MAC_HW_FEATURE0_MACADR64SEL  BIT(24)
#define MAC_HW_FEATURE0_MACADR32SEL  BIT(23)
#define MAC_HW_FEATURE0_ADDMACADRSEL GENMASK(22, 18)
#define MAC_HW_FEATURE0_RXCOESEL     BIT(16)
#define MAC_HW_FEATURE0_TXCOESEL     BIT(14)
#define MAC_HW_FEATURE0_EEESEL       BIT(13)
#define MAC_HW_FEATURE0_TSSEL        BIT(12)
#define MAC_HW_FEATURE0_ARPOFFSEL    BIT(9)
#define MAC_HW_FEATURE0_MMCSEL       BIT(8)
#define MAC_HW_FEATURE0_MGKSEL       BIT(7)
#define MAC_HW_FEATURE0_RWKSEL       BIT(6)
#define MAC_HW_FEATURE0_SMASEL       BIT(5)
#define MAC_HW_FEATURE0_VLHASH       BIT(4)
#define MAC_HW_FEATURE0_PCSSEL       BIT(3)
#define MAC_HW_FEATURE0_HDSEL        BIT(2)
#define MAC_HW_FEATURE0_GMIISEL      BIT(1)
#define MAC_HW_FEATURE0_MIISEL       BIT(0)

#define MAC_HW_FEATURE1 0x0120

#define MAC_HW_FEATURE1_L3L4FNUM   GENMASK(30, 27)
#define MAC_HW_FEATURE1_HASHTBLSZ  GENMASK(25, 24)
#define MAC_HW_FEATURE1_POUOST     BIT(23)
#define MAC_HW_FEATURE1_RAVSEL     BIT(21)
#define MAC_HW_FEATURE1_AVSEL      BIT(20)
#define MAC_HW_FEATURE1_DBGMEMA    BIT(19)
#define MAC_HW_FEATURE1_TSOEN      BIT(18)
#define MAC_HW_FEATURE1_SPHEN      BIT(17)
#define MAC_HW_FEATURE1_DCBEN      BIT(16)
#define MAC_HW_FEATURE1_ADDRESS64  GENMASK(15, 14)
#define MAC_HW_FEATURE1_ADVTHWORD  BIT(13)
#define MAC_HW_FEATURE1_PTOEN      BIT(12)
#define MAC_HW_FEATURE1_OSTEN      BIT(11)
#define MAC_HW_FEATURE1_TXFIFOSIZE GENMASK(10, 6)
#define MAC_HW_FEATURE1_SPRAM      BIT(5)
#define MAC_HW_FEATURE1_RXFIFOSIZE GENMASK(4, 0)

#define MAC_HW_FEATURE2 0x0124

#define MAC_HW_FEATURE2_AUXSNAPNUM GENMASK(30, 28)
#define MAC_HW_FEATURE2_PPSOUTNUM  GENMASK(28, 24)
#define MAC_HW_FEATURE2_TXCHCNT    GENMASK(21, 18)
#define MAC_HW_FEATURE2_RXCHCNT    GENMASK(15, 12)
#define MAC_HW_FEATURE2_TXQCNT     GENMASK(9, 6)
#define MAC_HW_FEATURE2_RXQCNT     GENMASK(3, 0)

#define MAC_HW_FEATURE3 0x0128

#define MAC_HW_FEATURE3_ASP     GENMASK(29, 28)
#define MAC_HW_FEATURE3_TBSSEL  BIT(27)
#define MAC_HW_FEATURE3_FPESEL  BIT(26)
#define MAC_HW_FEATURE3_ESTWID  GENMASK(21, 20)
#define MAC_HW_FEATURE3_ESTDEP  GENMASK(19, 17)
#define MAC_HW_FEATURE3_ESTSEL  BIT(16)
#define MAC_HW_FEATURE3_FRPES   GENMASK(14, 13)
#define MAC_HW_FEATURE3_FRPBS   GENMASK(12, 11)
#define MAC_HW_FEATURE3_FRPSEL  BIT(10)
#define MAC_HW_FEATURE3_PDUPSEL BIT(9)
#define MAC_HW_FEATURE3_DVLAN   BIT(5)
#define MAC_HW_FEATURE3_CBTISEL BIT(4)
#define MAC_HW_FEATURE3_NRVF    GENMASK(2, 0)

#define MAC_DPP_FSM_IRQ_STATUS 0x0140

#define MAC_DPP_FSM_IRQ_STATUS_FSMPES BIT(24)
#define MAC_DPP_FSM_IRQ_STATUS_SLVTES BIT(17)
#define MAC_DPP_FSM_IRQ_STATUS_MSTTES BIT(16)
#define MAC_DPP_FSM_IRQ_STATUS_RVCTES BIT(15)
#define MAC_DPP_FSM_IRQ_STATUS_R125ES BIT(14)
#define MAC_DPP_FSM_IRQ_STATUS_T125ES BIT(13)
#define MAC_DPP_FSM_IRQ_STATUS_PTES   BIT(12)
#define MAC_DPP_FSM_IRQ_STATUS_ATES   BIT(11)
#define MAC_DPP_FSM_IRQ_STATUS_CTES   BIT(10)
#define MAC_DPP_FSM_IRQ_STATUS_RTES   BIT(9)
#define MAC_DPP_FSM_IRQ_STATUS_TTES   BIT(8)
#define MAC_DPP_FSM_IRQ_STATUS_ASRPES BIT(7)
#define MAC_DPP_FSM_IRQ_STATUS_CWPES  BIT(6)
#define MAC_DPP_FSM_IRQ_STATUS_ARPES  BIT(5)
#define MAC_DPP_FSM_IRQ_STATUS_MTSPES BIT(4)
#define MAC_DPP_FSM_IRQ_STATUS_MPES   BIT(3)
#define MAC_DPP_FSM_IRQ_STATUS_RDPES  BIT(2)
#define MAC_DPP_FSM_IRQ_STATUS_TPES   BIT(1)
#define MAC_DPP_FSM_IRQ_STATUS_ATPES  BIT(0)

#define MAC_AXI_SLV_DPE_ADDRESS_STATUS 0x0144

#define MAC_AXI_SLV_DPE_ADDRESS_STATUS_ASPEAS GENMASK(13, 0)

#define MAC_FSM_CTRL 0x0148

#define MAC_FSM_CTRL_RVCLGRNML  BIT(31)
#define MAC_FSM_CTRL_R125LGRNML BIT(30)
#define MAC_FSM_CTRL_T125LGRNML BIT(29)
#define MAC_FSM_CTRL_PLGRNML    BIT(28)
#define MAC_FSM_CTRL_ALGRNML    BIT(27)
#define MAC_FSM_CTRL_CLGRNML    BIT(26)
#define MAC_FSM_CTRL_RLGRNML    BIT(25)
#define MAC_FSM_CTRL_TLGRNML    BIT(24)
#define MAC_FSM_CTRL_RVCPEIN    BIT(23)
#define MAC_FSM_CTRL_R125PEIN   BIT(22)
#define MAC_FSM_CTRL_T125PEIN   BIT(21)
#define MAC_FSM_CTRL_PPEIN      BIT(20)
#define MAC_FSM_CTRL_APEIN      BIT(19)
#define MAC_FSM_CTRL_CPEIN      BIT(18)
#define MAC_FSM_CTRL_RPEIN      BIT(17)
#define MAC_FSM_CTRL_TPEIN      BIT(16)
#define MAC_FSM_CTRL_RVCTEIN    BIT(15)
#define MAC_FSM_CTRL_R125TEIN   BIT(14)
#define MAC_FSM_CTRL_T125TEIN   BIT(13)
#define MAC_FSM_CTRL_PTEIN      BIT(12)
#define MAC_FSM_CTRL_ATEIN      BIT(11)
#define MAC_FSM_CTRL_CTEIN      BIT(10)
#define MAC_FSM_CTRL_RTEIN      BIT(9)
#define MAC_FSM_CTRL_TTEIN      BIT(8)
#define MAC_FSM_CTRL_PRTYEN     BIT(1)
#define MAC_FSM_CTRL_TMOUTEN    BIT(0)

#define MAC_FSM_ACT_TIMER 0x014c

#define MAC_FSM_ACT_TIMER_LTMRMD GENMASK(23, 20)
#define MAC_FSM_ACT_TIMER_NTMRMD GENMASK(19, 16)
#define MAC_FSM_ACT_TIMER_TMR    GENMASK(9, 0)

#define MAC_MDIO_ADDRESSESS 0x0200

#define MAC_MDIO_ADDRESSESS_PSE      BIT(27)
#define MAC_MDIO_ADDRESSESS_BTB      BIT(26)
#define MAC_MDIO_ADDRESSESS_PA       GENMASK(25, 21)
#define MAC_MDIO_ADDRESSESS_RDA      GENMASK(20, 16)
#define MAC_MDIO_ADDRESSESS_NTC      GENMASK(14, 12)
#define MAC_MDIO_ADDRESSESS_CR       BIT(11, 8)
#define MAC_MDIO_ADDRESSESS_SKAP     BIT(4)
#define MAC_MDIO_ADDRESSESS_GOC_1    BIT(3)
#define MAC_MDIO_ADDRESSESS_GOC_0    BIT(2)
#define MAC_MDIO_ADDRESSESS_GOC_C45E BIT(1)
#define MAC_MDIO_ADDRESSESS_GOC_GB   BIT(0)

#define MAC_MDIO_DATA 0x0204

#define MAC_MDIO_DATA_RA GENMASK(31, 16)
#define MAC_MDIO_DATA_GD GENMASK(15, 0)

#define MAC_GPIO_CTRL 0x0208

#define MAC_GPIO_STATUS 0x020c

#define MAC_ARP_ADDRESSESS 0x0210

#define MAC_CSR_SW_CTRL 0x0230

#define MAC_FPE_CTRL_STS 0x0234

#define MAC_EXT_CFG1 0x0238

#define MAC_EXT_CFG1_SPLM    GENMASK(9, 8)
#define MAC_EXT_CFG1_SPLOFST GENMASK(6, 0)

#define MAC_PRESN_TIME_NS 0x0240

#define MAC_PRESN_TIME_UPDT 0x0244

#define MAC_ADDRESSi_HIGH(i) (0x0300 + 8 * (i))

#define MAC_ADDRESSi_HIGH_ADDRESSHI GENMASK(15, 0)
#define MAC_ADDRESSi_HIGH_DCS       GENMASK(18, 16)
#define MAC_ADDRESSi_HIGH_MBC       GENMASK(29, 24)
#define MAC_ADDRESSi_HIGH_SA        BIT(30)
#define MAC_ADDRESSi_HIGH_AE        BIT(31)

#define MAC_ADDRESSi_LOW(i) (0x0304 + 8 * (i))

#define MMC_RX_INTERRUPT_MASK     (0x70C)
#define MMC_TX_INTERRUPT_MASK     (0x710)
#define MMC_IPC_RX_INTERRUPT_MASK (0x800)
#define MMC_FPE_TX_INTERRUPT_MASK (0x8a4)
#define MMC_FPE_RX_INTERRUPT_MASK (0x8c0)

#define MAC_INDIR_ACCESS_CTRL        0x0a70
#define MAC_INDIR_ACCESS_CTRL_SNPS_R BIT(31)
#define MAC_INDIR_ACCESS_CTRL_MSEL   GENMASK(19, 16)
#define MAC_INDIR_ACCESS_CTRL_AOFF   GENMASK(15, 8)
#define MAC_INDIR_ACCESS_CTRL_AUTO   BIT(5)
#define MAC_INDIR_ACCESS_CTRL_COM    BIT(1)
#define MAC_INDIR_ACCESS_CTRL_OB     BIT(0)

#define MAC_INDIR_ACCESS_DATA 0x0a74

#define MAC_SYSTEM_TIME_HIGHER_WORD_SECONDS       0xb1c
#define MAC_SYSTEM_TIME_HIGHER_WORD_SECONDS_TSHWR GENMASK(15, 0)

#define MAC_TIMESTAMP_STATUS            0xb20
#define MAC_TIMESTAMP_STATUS_TSSOVF     BIT(0)
#define MAC_TIMESTAMP_STATUS_TSTARGT0   BIT(1)
#define MAC_TIMESTAMP_STATUS_AUXTSTRIG  BIT(2)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR0 BIT(3)
#define MAC_TIMESTAMP_STATUS_TSTARGT1   BIT(4)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR1 BIT(5)
#define MAC_TIMESTAMP_STATUS_TSTARGT2   BIT(6)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR2 BIT(7)
#define MAC_TIMESTAMP_STATUS_TSTARGT3   BIT(8)
#define MAC_TIMESTAMP_STATUS_TSTRGTERR3 BIT(9)
#define MAC_TIMESTAMP_STATUS_TXTSSIS    BIT(15)
#define MAC_TIMESTAMP_STATUS_ATSSTN     GENMASK(19, 16)
#define MAC_TIMESTAMP_STATUS_ATSSTM     BIT(24)
#define MAC_TIMESTAMP_STATUS_ATSNS      GENMASK(29, 25)

#define MAC_TX_TIMESTAMP_STATUS_NANOSECONDS          0xb30
#define MAC_TX_TIMESTAMP_STATUS_NANOSECONDS_TXTSSLO  GENMASK(30, 0)
#define MAC_TX_TIMESTAMP_STATUS_NANOSECONDS_TXTSSMIS BIT(31)
#define MAC_TX_TIMESTAMP_STATUS_SECONDS              0xb34

/*
 * MTL Register Definitions
 */

#define MTL_OPERATION_MODE            0x0c00
#define MTL_OPERATION_MODE_SCHALG_POS 5
#define MTL_OPERATION_MODE_SCHALG     GENMASK(6, MTL_OPERATION_MODE_SCHALG_POS)
#define MTL_OPERATION_MODE_RAA        BIT(2)
#define MTL_OPERATION_MODE_DTXSTS     BIT(1)

enum {
	MTL_OPERATION_MODE_SCHALG_WRR,
	MTL_OPERATION_MODE_SCHALG_WFQ,
	MTL_OPERATION_MODE_SCHALG_DWRR,
	MTL_OPERATION_MODE_SCHALG_STRICT
};

#define MTL_DBG_CTL 0x0c08

#define MTL_DBG_STS 0x0c0c

#define MTL_FIFO_DEBUG_DATA 0x0c10

#define MTL_INTERRUPT_STATUS 0x0c20

#define MTL_INTERRUPT_STATUS_MTLPIS BIT(23)
#define MTL_INTERRUPT_STATUS_ESTIS  BIT(18)
#define MTL_INTERRUPT_STATUS_DBGIS  BIT(17)
#define MTL_INTERRUPT_STATUS_MACIS  BIT(16)
#define MTL_INTERRUPT_STATUS_Q7IS   BIT(7)
#define MTL_INTERRUPT_STATUS_Q6IS   BIT(6)
#define MTL_INTERRUPT_STATUS_Q5IS   BIT(5)
#define MTL_INTERRUPT_STATUS_Q4IS   BIT(4)
#define MTL_INTERRUPT_STATUS_Q3IS   BIT(3)
#define MTL_INTERRUPT_STATUS_Q2IS   BIT(2)
#define MTL_INTERRUPT_STATUS_Q1IS   BIT(1)
#define MTL_INTERRUPT_STATUS_Q0IS   BIT(0)

#define MTL_RXQ_DMA_MAP0 0x0c30

#define MTL_RXQ_DMA_MAP1 0x0c34

#define MTL_TBS_CTRL 0x0c40

#define MTL_EST_CTRL 0x0c50

#define MTL_EST_STATUS 0x0c58

#define MTL_EST_SCH_ERROR 0x0c60

#define MTL_EST_FRM_SIZE_ERROR 0x0c64

#define MTL_EST_FRM_SIZE_CAPTURE 0x0c68

#define MTL_EST_INTERRUPT_ENABLE 0x0c70

#define MTL_EST_GCL_CONTROL 0x0c80

#define MTL_EST_GCL_DATA 0x0c84

#define MTL_FPE_CTRL_STS 0x0c90

#define MTL_FPE_ADVANCE 0x0c94

#define MTL_RXP_CTRL_STATUS 0x0ca0

#define MTL_RXP_IRQ_CTRL_STATUS 0x0ca4

#define MTL_RXP_DROP_CNT 0x0ca8

#define MTL_RXP_ERROR_CNT 0x0cac

#define MTL_RXP_INDIRECT_ACC_CTRL_STATUS 0x0cb0

#define MTL_RXP_INDIRECT_ACC_DATA 0x0cb4

#define MTL_ECC_CTRL 0x0cc0

#define MTL_SAFETY_IRQ_STATUS 0x0cc4

#define MTL_ECC_INTERRUPT_ENABLE 0x0cc8

#define MTL_ECC_IRQ_STATUS 0x0ccc

#define MTL_ECC_ERR_STS_RCTL 0x0cd0

#define MTL_ECC_ERR_ADDRESS_STATUS 0x0cd4

#define MTL_ECC_ERR_CNTR_STATUS 0x0cd8

#define MTL_DPP_CTRL 0x0ce0

#define MTL_TXQi_OPERATION_MODE(i)    (0x0d00 + 0x40 * (i))
#define MTL_TXQi_OPERATION_MODE_TQS   GENMASK(31, 16)
#define MTL_TXQi_OPERATION_MODE_TTC   GENMASK(6, 4)
#define MTL_TXQi_OPERATION_MODE_TXQEN BIT(3)
#define MTL_TXQi_OPERATION_MODE_TSF   BIT(1)
#define MTL_TXQi_OPERATION_MODE_FTQ   BIT(0)

#define MTL_TXQi_UNDERFLOW(i) (0x0d04 + 0x40 * (i))

#define MTL_TXQi_DEBUG(i) (0x0d08 + 0x40 * (i))

#define MTL_TXQi_ETS_CTRL(i) (0x0d10 + 0x40 * (i))

#define MTL_TXQi_ETS_STATUS(i) (0x0d14 + 0x40 * (i))

#define MTL_TXQi_QUANTUM_WEIGHT(i) (0x0d18 + 0x40 * (i))

#define MTL_TXQi_SENDSLOPECREDIT(i) (0x0d1c + 0x40 * (i))

#define MTL_TXQi_HICREDIT(i) (0x0d20 + 0x40 * (i))

#define MTL_TXQi_LOCREDIT(i) (0x0d24 + 0x40 * (i))

#define MTL_Qn_IRQ_CTRL_STATUS(i) (0x0d2c + 0x40 * (i))

#define MTL_RXQi_OPERATION_MODE(i)      (0x0d30 + 0x40 * (i))
#define MTL_RXQi_OPERATION_MODE_RQS_POS 20
#define MTL_RXQi_OPERATION_MODE_RQS     GENMASK(31, MTL_RXQi_OPERATION_MODE_RQS_POS)
#define MTL_RXQi_OPERATION_MODE_RFD_POS 14
#define MTL_RXQi_OPERATION_MODE_RFD     GENMASK(19, 14)
#define MTL_RXQi_OPERATION_MODE_RFA_POS 8
#define MTL_RXQi_OPERATION_MODE_RFA     GENMASK(13, MTL_RXQi_OPERATION_MODE_RQS_POS)
#define MTL_RXQi_OPERATION_MODE_RSF     BIT(5)
#define MTL_RXQi_OPERATION_MODE_FEP     BIT(4)
#define MTL_RXQi_OPERATION_MODE_FUP     BIT(3)
#define MTL_RXQi_OPERATION_MODE_RTC_POS 0
#define MTL_RXQi_OPERATION_MODE_RTC     GENMASK(1, MTL_RXQi_OPERATION_MODE_RTC_POS)
enum {
	MTL_RXQi_OPERATION_MODE_RTC_64,
	MTL_RXQi_OPERATION_MODE_RTC_32,
	MTL_RXQi_OPERATION_MODE_RTC_96,
	MTL_RXQi_OPERATION_MODE_RTC_128
};

#define MTL_RXQi_MISSED_PKT_OVFL_CNT(i) (0x0d34 + 0x40 * (i))

#define MTL_RXQi_DEBUG(i) (0x0d38 + 0x40 * (i))

#define MTL_RXQi_CTRL(i) (0x0d3c + 0x40 * (i))

/*
 * DMA Register Definitions
 */

#define DMA_MODE 0x1000

#define DMA_MODE_INTM GENMASK(17, 16)
#define DMA_MODE_PR   GENMASK(14, 12)
#define DMA_MODE_TXPR BIT(12)
#define DMA_MODE_ARBC BIT(9)
#define DMA_MODE_DSPW BIT(8)
#define DMA_MODE_TAA  GENMASK(4, 2)
#define DMA_MODE_DA   BIT(1)
#define DMA_MODE_SWR  BIT(0)

#define DMA_SYSBUS_MODE 0x1004

#define DMA_SYSBUS_MODE_EN_LPI      BIT(31)
#define DMA_SYSBUS_MODE_LPI_XIT_PKT BIT(30)
#define DMA_SYSBUS_MODE_WR_OSR_LMT  GENMASK(27, 24)
#define DMA_SYSBUS_MODE_RD_OSR_LMT  GENMASK(19, 16)
#define DMA_SYSBUS_MODE_RB          BIT(15)
#define DMA_SYSBUS_MODE_MB          BIT(14)
#define DMA_SYSBUS_MODE_ONEKBBE     BIT(13)
#define DMA_SYSBUS_MODE_AAL         BIT(12)
#define DMA_SYSBUS_MODE_EAME        BIT(11)
#define DMA_SYSBUS_MODE_AALE        BIT(10)
#define DMA_SYSBUS_MODE_BLEN256     BIT(7)
#define DMA_SYSBUS_MODE_BLEN128     BIT(6)
#define DMA_SYSBUS_MODE_BLEN64      BIT(5)
#define DMA_SYSBUS_MODE_BLEN32      BIT(4)
#define DMA_SYSBUS_MODE_BLEN16      BIT(3)
#define DMA_SYSBUS_MODE_BLEN8       BIT(2)
#define DMA_SYSBUS_MODE_BLEN4       BIT(1)
#define DMA_SYSBUS_MODE_FB          BIT(0)

#define DMA_INTERRUPT_STATUS 0x1008

#define DMA_INTERRUPT_STATUS_MACIS BIT(17)
#define DMA_INTERRUPT_STATUS_MTLIS BIT(16)
#define DMA_INTERRUPT_STATUS_DC7IS BIT(7)
#define DMA_INTERRUPT_STATUS_DC6IS BIT(6)
#define DMA_INTERRUPT_STATUS_DC5IS BIT(5)
#define DMA_INTERRUPT_STATUS_DC4IS BIT(4)
#define DMA_INTERRUPT_STATUS_DC3IS BIT(3)
#define DMA_INTERRUPT_STATUS_DC2IS BIT(2)
#define DMA_INTERRUPT_STATUS_DC1IS BIT(1)
#define DMA_INTERRUPT_STATUS_DC0IS BIT(0)

#define DMA_DEBUG_STATUS0 0x100c

#define DMA_DEBUG_STATUS1 0x1010

#define DMA_DEBUG_STATUS2 0x1014

#define AXI4_TX_AR_ACE_CTRL 0x1020

#define AXI4_RX_AW_ACE_CTRL 0x1024

#define AXI4_TXRX_AWAR_ACE_CTRL 0x1028

#define AXI_LPI_ENTRY_INTERVAL 0x1040

#define DMA_TBS_CTRL 0x1050

#define DMA_SAFETY_IRQ_STATUS 0x1080

#define DMA_ECC_INTERRUPT_ENABLE 0x1084

#define DMA_ECC_IRQ_STATUS 0x1088

#define DMA_CHi_CTRL(i) (0x1100 + 0x80 * (i))

#define DMA_CHi_CTRL_SPH   BIT(24)
#define DMA_CHi_CTRL_DSL   GENMASK(20, 18)
#define DMA_CHi_CTRL_PBLx8 BIT(16)
#define DMA_CHi_CTRL_MSS   GENMASK(13, 0)

#define DMA_CHi_TX_CONTROL(i) (0x1104 + 0x80 * (i))

#define DMA_CHi_TX_CONTROL_EDSE     BIT(28)
#define DMA_CHi_TX_CONTROL_TQOS     GENMASK(27, 24)
#define DMA_CHi_TX_CONTROL_ETIC     BIT(22)
#define DMA_CHi_TX_CONTROL_PBL      GENMASK(21, 16)
#define DMA_CHi_TX_CONTROL_IPBL     BIT(15)
#define DMA_CHi_TX_CONTROL_TSE_MODE GENMASK(14, 13)
#define DMA_CHi_TX_CONTROL_TSE      BIT(12)
#define DMA_CHi_TX_CONTROL_OSF      BIT(4)
#define DMA_CHi_TX_CONTROL_TCW      GENMASK(3, 1)
#define DMA_CHi_TX_CONTROL_ST       BIT(0)

#define DMA_CHi_RX_CONTROL(i) (0x1108 + 0x80 * (i))

#define DMA_CHi_RX_CONTROL_RPF  BIT(31)
#define DMA_CHi_RX_CONTROL_RQOS GENMASK(27, 24)
#define DMA_CHi_RX_CONTROL_ERIC BIT(22)
#define DMA_CHi_RX_CONTROL_PBL  GENMASK(21, 16)
#define DMA_CHi_RX_CONTROL_RBSZ GENMASK(14, 1)
#define DMA_CHi_RX_CONTROL_SR   BIT(0)

#define DMA_CHi_TXDESC_LIST_HADDRESS(i) (0x1110 + 0x80 * (i))

#define DMA_CHi_TXDESC_LIST_ADDRESS(i) (0x1114 + 0x80 * (i))

#define DMA_CHi_RXDESC_LIST_HADDRESS(i) (0x1118 + 0x80 * (i))

#define DMA_CHi_RXDESC_LIST_ADDRESS(i) (0x111c + 0x80 * (i))

#define DMA_CHi_TXDESC_TAIL_POINTER(i) (0x1120 + 0x80 * (i))

#define DMA_CHi_RXDESC_TAIL_POINTER(i) (0x1128 + 0x80 * (i))

#define DMA_CHi_TXDESC_RING_LENGTH(i)   (0x112c + 0x80 * (i))
#define DMA_CHi_TXDESC_RING_LENGTH_TDRL GENMASK(9, 0)

#define DMA_CHi_RXDESC_RING_LENGTH(i)   (0x1130 + 0x80 * (i))
#define DMA_CHi_RXDESC_RING_LENGTH_RDRL GENMASK(9, 0)

#define DMA_CHi_INTERRUPT_ENABLE(i) (0x1134 + 0x80 * (i))

#define DMA_CHi_INTERRUPT_ENABLE_NIE  BIT(15)
#define DMA_CHi_INTERRUPT_ENABLE_AIE  BIT(14)
#define DMA_CHi_INTERRUPT_ENABLE_CDEE BIT(13)
#define DMA_CHi_INTERRUPT_ENABLE_FBEE BIT(12)
#define DMA_CHi_INTERRUPT_ENABLE_ERIE BIT(11)
#define DMA_CHi_INTERRUPT_ENABLE_ETIE BIT(10)
#define DMA_CHi_INTERRUPT_ENABLE_RWTE BIT(9)
#define DMA_CHi_INTERRUPT_ENABLE_RSE  BIT(8)
#define DMA_CHi_INTERRUPT_ENABLE_RBUE BIT(7)
#define DMA_CHi_INTERRUPT_ENABLE_RIE  BIT(6)
#define DMA_CHi_INTERRUPT_ENABLE_TBUE BIT(2)
#define DMA_CHi_INTERRUPT_ENABLE_TXSE BIT(1)
#define DMA_CHi_INTERRUPT_ENABLE_TIE  BIT(0)

#define DMA_CHi_RX_IRQ_WATCHDOG_TIMER(i) (0x1138 + 0x80 * (i))
#define DMA_CHi_SLOT_FN_CTRL_STATUS(i) (0x113c + 0x80 * (i))
#define DMA_CHi_CURR_APP_TXDESC(i) (0x1144 + 0x80 * (i))
#define DMA_CHi_CURR_APP_RXDESC(i) (0x114c + 0x80 * (i))
#define DMA_CHi_CURR_APP_TX_BUF_H(i) (0x1150 + 0x80 * (i))
#define DMA_CHi_CURR_APP_TX_BUF(i) (0x1154 + 0x80 * (i))
#define DMA_CHi_CURR_APP_RX_BUF_H(i) (0x1158 + 0x80 * (i))
#define DMA_CHi_CURR_APP_RX_BUF(i) (0x115c + 0x80 * (i))

#define DMA_CHi_STATUS(i) (0x1160 + 0x80 * (i))

#define DMA_CHi_STATUS_REB GENMASK(21, 19)
#define DMA_CHi_STATUS_TEB GENMASK(18, 16)
#define DMA_CHi_STATUS_NIS BIT(15)
#define DMA_CHi_STATUS_AIS BIT(14)
#define DMA_CHi_STATUS_CDE BIT(13)
#define DMA_CHi_STATUS_FBE BIT(12)
#define DMA_CHi_STATUS_ERI BIT(11)
#define DMA_CHi_STATUS_ETI BIT(10)
#define DMA_CHi_STATUS_RWT BIT(9)
#define DMA_CHi_STATUS_RPS BIT(8)
#define DMA_CHi_STATUS_RBU BIT(7)
#define DMA_CHi_STATUS_RI  BIT(6)
#define DMA_CHi_STATUS_TBU BIT(2)
#define DMA_CHi_STATUS_TPS BIT(1)
#define DMA_CHi_STATUS_TI  BIT(0)

#define DMA_CHi_MISS_FRAME_CNT(i) (0x1164 + 0x80 * (i))
#define DMA_CHi_RXP_ACCEPT_CNT(i) (0x1168 + 0x80 * (i))
#define DMA_CHi_RX_ERI_CNT(i) (0x116c + 0x80 * (i))

#endif
